#!/usr/bin/env python3

if __name__ == '__main__':
    Score = 0

    Q1 = input("Please type Y if answer correct, If incorrect type N: ")
    Q1 = Q1.capitalize()
    if Q1 == 'Y':
        Score = Score + 1
    Q2 = input("Please type Y if answer correct, If incorrect type N: ")
    Q2 = Q2.capitalize()
    if Q2 == 'Y':
        Score = Score + 1
    Q3 = input("Please type Y if answer correct, If incorrect type N: ")
    Q3 = Q3.capitalize()
    if Q3 == 'Y':
        Score = Score + 1
    Q4 = input("Please type Y if answer correct, If incorrect type N: ")
    Q4 = Q4.capitalize()
    if Q4 == 'Y':
        Score = Score + 1
    Q5 = input("Please type Y if answer correct, If incorrect type N: ")
    Q5 = Q5.capitalize()
    if Q5 == 'Y':
        Score = Score + 1
    Q6 = input("Please type Y if answer correct, If incorrect type N: ")
    Q6 = Q6.capitalize()
    if Q6 == 'Y':
        Score = Score + 1
    Q7 = input("Please type Y if answer correct, If incorrect type N: ")
    Q7 = Q7.capitalize()
    if Q7 == 'Y':
        Score = Score + 1
    Q8 = input("Please type Y if answer correct, If incorrect type N: ")
    Q8 = Q8.capitalize()
    if Q8 == 'Y':
        Score = Score + 1
    Q9 = input("Please type Y if answer correct, If incorrect type N: ")
    Q9 = Q9.capitalize()
    if Q9 == 'Y':
        Score = Score + 1
    Q10 = input("Please type Y if answer correct, If incorrect type N: ")
    Q10 = Q10.capitalize()
    if Q10 == 'Y':
        Score = Score + 1
    Q11 = input("Please type Y if answer correct, If incorrect type N: ")
    Q11 = Q11.capitalize()
    if Q11 == 'Y':
        Score = Score + 1
    Q12 = input("Please type Y if answer correct, If incorrect type N: ")
    Q12 = Q12.capitalize()
    if Q12 == 'Y':
        Score = Score + 1
    Q13 = input("Please type Y if answer correct, If incorrect type N: ")
    Q13 = Q13.capitalize()
    if Q13 == 'Y':
        Score = Score + 1
    Q14 = input("Please type Y if answer correct, If incorrect type N: ")
    Q14 = Q14.capitalize()
    if Q14 == 'Y':
        Score = Score + 1
    Q15 = input("Please type Y if answer correct, If incorrect type N: ")
    Q15 = Q15.capitalize()
    if Q15 == 'Y':
        Score = Score + 1
    print("Your Score is: ", Score, "/ 15")
    print(Score / 15 * 100, "%")
    if Score < 10:
        print("You have failed the test please retake the test. ")
    else:
        print("You Have passed, Well Done.")
        print("Congratulations")
